from __future__ import annotations

KNOWN_SOURCE_DEFINITIONS = [
    {"source_id":"google_sheet","source_name":"Google Sheet stock universe","source_type":"stock_universe","provider":"Google Sheets","credential_required":True,"freshness_policy":"manual_or_runtime_refresh","source_priority":"A_primary","evidence":["app/loaders/google_sheet_loader.py","orchestrator/templates/source_inventory_registry.example.json"]},
    {"source_id":"shioaji_sinopac","source_name":"Shioaji / Sinopac","source_type":"broker_market_data","provider":"Sinopac Shioaji","credential_required":True,"freshness_policy":"market_session","source_priority":"A_primary","evidence":["app/market/shioaji_client.py","orchestrator/templates/source_inventory_registry.example.json"]},
    {"source_id":"twse_openapi","source_name":"TWSE","source_type":"exchange_openapi","provider":"TWSE","credential_required":False,"freshness_policy":"daily","source_priority":"B_official_or_company_linked","evidence":["app/sources/twse_openapi_connector.py","app/sources/endpoint_registry.py"]},
    {"source_id":"google_news_rss","source_name":"Google News RSS","source_type":"news_rss","provider":"Google News","credential_required":False,"freshness_policy":"event_driven","source_priority":"D_low_priority_metadata_noise","evidence":["orchestrator/templates/source_inventory_registry.example.json","app/prediction/source_inventory.py"]},
    {"source_id":"yfinance_yahoo","source_name":"yfinance / Yahoo","source_type":"market_context","provider":"Yahoo Finance / yfinance","credential_required":False,"freshness_policy":"market_day","source_priority":"C_market_or_industry","evidence":["app/sources/yfinance_market_context.py","app/market/adr_loader.py"]},
    {"source_id":"gemini_google_generative_ai","source_name":"Gemini / Google Generative AI","source_type":"llm_summary","provider":"Google Generative AI","credential_required":True,"freshness_policy":"on_demand","source_priority":"D_low_priority_metadata_noise","evidence":["orchestrator/templates/source_inventory_registry.example.json","app/prediction/source_inventory.py"]},
    {"source_id":"sqlite_historical_csv","source_name":"SQLite / historical CSV","source_type":"local_storage","provider":"repo_local","credential_required":False,"freshness_policy":"repo_local_or_pipeline_artifact","source_priority":"A_primary","evidence":["app/database/sqlite_client.py","app/market/historical_csv_loader.py","app/market/historical_price_loader.py"]},
    {"source_id":"mops_public_information_observatory","source_name":"MOPS / 公開資訊觀測站","source_type":"official_filing","provider":"MOPS","credential_required":False,"freshness_policy":"event_or_periodic","source_priority":"B_official_or_company_linked","evidence":["orchestrator/templates/source_inventory_registry.example.json","app/prediction/source_inventory.py"]},
    {"source_id":"company_announcements","source_name":"公司公告","source_type":"company_disclosure","provider":"Company / MOPS","credential_required":False,"freshness_policy":"event_driven","source_priority":"B_official_or_company_linked","evidence":["app/prediction/source_inventory.py"]},
    {"source_id":"financial_statements","source_name":"財報","source_type":"fundamental_filing","provider":"MOPS / company filings","credential_required":False,"freshness_policy":"quarterly","source_priority":"B_official_or_company_linked","evidence":["app/prediction/source_inventory.py"]},
    {"source_id":"investor_conference","source_name":"法說會 / investor conference","source_type":"company_event","provider":"MOPS / company IR","credential_required":False,"freshness_policy":"event_driven","source_priority":"B_official_or_company_linked","evidence":["app/prediction/source_inventory.py"]},
    {"source_id":"management_interviews","source_name":"管理層訪談","source_type":"media_interview","provider":"company_or_media","credential_required":False,"freshness_policy":"event_driven","source_priority":"D_low_priority_metadata_noise","evidence":["app/prediction/source_inventory.py"]},
    {"source_id":"industry_supply_chain","source_name":"產業上下游資料","source_type":"industry_context","provider":"industry research","credential_required":False,"freshness_policy":"weekly_or_monthly","source_priority":"C_market_or_industry","evidence":["app/prediction/source_inventory.py"]},
    {"source_id":"etf_index_sector_proxy","source_name":"ETF / index / sector proxy","source_type":"market_proxy","provider":"TWSE / ETF issuer / Yahoo","credential_required":False,"freshness_policy":"market_day","source_priority":"C_market_or_industry","evidence":["app/prediction/source_inventory.py","app/sources/yfinance_market_context.py"]},
    {"source_id":"analyst_target_broker_opinion","source_name":"analyst target price / broker opinion","source_type":"analyst_opinion","provider":"broker_research","credential_required":True,"freshness_policy":"event_driven","source_priority":"D_low_priority_metadata_noise","evidence":[]},
]
