"""Controlled route integration artifact for the four-window dashboard preview."""
from __future__ import annotations
import json
from html import escape
from pathlib import Path
from typing import Any
SCHEMA_VERSION='four_window_dashboard_route_integration_v1'; TASK_ID='AI-DEV-144'; GENERATED_AT='2026-07-05T00:00:00Z'; ROUTE_PATH='/dashboard/decision-intelligence/four-window-preview'
SOURCE_PREVIEW_ARTIFACT='templates/four_window_decision_intelligence_dashboard_artifact.example.json'; SOURCE_PREVIEW_HTML='templates/four_window_decision_intelligence_dashboard_preview.example.html'; ROUTE_HTML='templates/four_window_dashboard_route_preview.example.html'
REPO_ROOT=Path(__file__).resolve().parents[2]; RUNTIME_DATA='templates/four_window_dashboard_runtime_data.example.json'
SAFETY_POLICY={'controlled_static_route':True,'repo_side_preview_only':True,'external_api_called':False,'secrets_read':False,'db_write':False,'scheduler_modified':False,'external_notification_sent':False,'line_email_notification_sent':False,'production_pipeline_executed':False,'python_main_executed':False,'trading_or_order_executed':False,'production_dashboard_publish_executed':False,'dashboard_published':False,'formal_delivery_behavior_changed':False,'direct_rating_action_confidence_impact':False,'production_rating_action_confidence_weight_mutated':False}
ROLLBACK_INSTRUCTIONS=['Remove the controlled dashboard route mapping from the future dashboard router.','Restore the previous dashboard preview route configuration.','Keep scheduler, notification delivery, production pipeline, and DB state untouched.','Re-run route integration and post-merge validators after rollback.']
def load_json(path:Path)->dict[str,Any]: return json.loads(path.read_text(encoding='utf-8'))
def build_input()->dict[str,Any]: return {'schema_version':'four_window_dashboard_route_integration_input_v1','task_id':TASK_ID,'generated_at':GENERATED_AT,'route_path':ROUTE_PATH,'source_preview_artifact':SOURCE_PREVIEW_ARTIFACT,'source_preview_html':SOURCE_PREVIEW_HTML,'controlled_route_only':True,'production_publish_allowed':False}
def _window_mapping(preview:dict[str,Any])->list[dict[str,Any]]:
    return [{'window_key':w.get('window_key'),'ui_window_id':w.get('ui_window_id'),'ui_display_name_zh':w.get('ui_display_name_zh'),'ui_display_name_en':w.get('ui_display_name_en'),'scheduled_time_tw':w.get('scheduled_time_tw'),'market_phase':w.get('market_phase'),'primary_purpose':w.get('primary_purpose'),'full_prediction_review_assigned':w.get('ui_window_id')=='prediction_review_1500'} for w in preview.get('four_window_content_contract',[])]
def build_artifact(payload:dict[str,Any]|None=None,repo_root:Path|None=None)->dict[str,Any]:
    repo_root=repo_root or Path.cwd(); payload=payload or build_input(); preview_ref=payload.get('source_preview_artifact',SOURCE_PREVIEW_ARTIFACT); html_ref=payload.get('source_preview_html',SOURCE_PREVIEW_HTML); preview=load_json(repo_root/preview_ref)
    return {'schema_version':SCHEMA_VERSION,'task_id':TASK_ID,'generated_at':payload.get('generated_at',GENERATED_AT),'route_path':payload.get('route_path',ROUTE_PATH),'route_id':'four_window_decision_intelligence_preview_route','route_kind':'controlled_static_dashboard_preview','source_preview_artifact':preview_ref,'source_preview_html':html_ref,'route_preview_html':ROUTE_HTML,'four_window_mapping':_window_mapping(preview),'semantic_rules':{'pre_open_0700_is_pre_open_forecast':True,'intraday_1305_is_intraday_tracking':True,'pre_close_1335_runtime_key_compatible':True,'pre_close_1335_ui_id':'close_snapshot_1335','pre_close_1335_ui_label_zh':'收盤快照','pre_close_1335_ui_label_en':'Close Snapshot','pre_close_1335_primary_ui_must_not_be_pre_close':True,'full_prediction_review_window_key':'post_close_1500','full_prediction_review_ui_id':'prediction_review_1500'},'route_integration_status':{'static_controlled_route_artifact_created':True,'production_dashboard_publish_executed':False,'dashboard_published':False,'external_notification_sent':False,'scheduler_modified':False,'production_pipeline_executed':False,'db_write':False},'validation_gates':['validate_four_window_decision_intelligence_dashboard_ui_v1','validate_four_window_dashboard_preview_review_v1','validate_four_window_dashboard_route_integration_v1','validate_post_merge_status'],'rollback_instructions':ROLLBACK_INSTRUCTIONS,'safety_policy':SAFETY_POLICY}
def badge(status:str)->str: return 'safe' if status in {'fresh','always_current'} else 'warn' if status in {'stale','missing'} else ''
def cards(items:list[dict[str,Any]],kind:str)->str:
    out=[]
    for item in items:
        if not isinstance(item,dict): continue
        if kind=='report':
            title=item.get('report_window') or item.get('data_state') or 'report'; lines=[f"產生時間：{item.get('generated_timestamp') or 'missing'}",f"股票數：{item.get('stock_count') if item.get('stock_count') is not None else 'missing'}",f"已接區塊：{', '.join(item.get('report_sections_available') or ['資料待接'])}",f"缺少區塊：{', '.join(item.get('missing_sections') or ['無'])}",str(item.get('summary') or '')]; st=str(item.get('freshness_status') or 'missing')
        elif kind=='stock':
            title=f"{item.get('stock_id') or 'missing'} {item.get('stock_name') or ''}"; lines=[f"時間：{item.get('generated_at') or 'missing'}",f"分數：{item.get('total_score') if item.get('total_score') is not None else '資料待接'}",f"評等：{item.get('rating') or '資料待接'} / 動作：{item.get('action') or '資料待接'}",f"風險：{item.get('risk_summary') or '資料待接'}"]; st=str(item.get('freshness_status') or 'missing')
        elif kind=='field':
            title=item.get('label') or item.get('field') or 'field'; lines=[str(item.get('message') or item.get('data_state') or '資料待接')]; st=str(item.get('freshness_status') or 'missing')
        elif kind=='fresh':
            title=f"{item.get('category')} / {item.get('id')}"; lines=[f"timestamp: {item.get('timestamp') or 'missing'}",f"max age: {item.get('max_age_hours')}h"]; st=str(item.get('status') or 'missing')
        else:
            title=item.get('label') or item.get('source_family') or 'source'; lines=[f"可信度：{item.get('quality') or item.get('credibility')}",f"用途：{item.get('allowed_usage')}"]; st=str(item.get('freshness_status') or 'always_current')
        out.append('<div class="source-item"><h3>'+escape(str(title))+'</h3>'+''.join('<p>'+escape(str(x))+'</p>' for x in lines if x)+'<span class="badge '+badge(st)+'">'+escape(st)+'</span></div>')
    return ''.join(out) if out else '<div class="source-item"><h3>資料待接</h3><p>目前尚未找到可用資料。</p><span class="badge warn">missing</span></div>'
def render_route_html(artifact:dict[str,Any],preview_html:str)->str:
    runtime=load_json(REPO_ROOT/RUNTIME_DATA) if (REPO_ROOT/RUNTIME_DATA).exists() else {}; route_path=escape(str(artifact['route_path'])); status_map={'fresh':'資料正常','partial_data':'部分缺資料','stale':'資料過期','missing':'尚未接資料','preview_only':'預覽資料'}
    global_status=escape(status_map.get(str(runtime.get('global_freshness_status','preview_only')),'預覽資料')); latest_ts=escape(str(runtime.get('latest_data_timestamp') or '資料待接'))
    stocks=runtime.get('stock_universe',[]) if isinstance(runtime.get('stock_universe'),list) else []; stock_rows=[s for s in stocks if isinstance(s,dict) and s.get('stock_id')]; usable=len([s for s in stock_rows if s.get('data_state')=='usable']); missing=len(runtime.get('missing_data',[])) if isinstance(runtime.get('missing_data'),list) else 0; stale=len(runtime.get('stale_data',[])) if isinstance(runtime.get('stale_data'),list) else 0
    prediction_available='否，資料待接' if any(isinstance(p,dict) and p.get('freshness_status')=='missing' for p in runtime.get('prediction_fields',[])) else '是'
    window_cards=[]
    for w in runtime.get('four_windows',[]):
        if not isinstance(w,dict): continue
        purpose='Full prediction review / 完整盤後檢討' if w.get('full_prediction_review') else '查看此時段的決策資料狀態'
        if w.get('window_key')=='pre_close_1335': purpose='收盤快照；完整檢討待 15:00'
        window_cards.append(f'<article class="card window-card"><div class="window-time">{escape(str(w.get("expected_time")))}</div><div class="window-title">{escape(str(w.get("display_name")))}</div><p><strong>用途：</strong>{escape(purpose)}</p><p><strong>最新資料：</strong>{escape(str(w.get("latest_available_data_timestamp") or "資料待接"))}</p><p><strong>已接區塊：</strong>{escape(", ".join(w.get("available_sections") or ["目前尚未找到可用資料"]))}</p><p><strong>缺少區塊：</strong>{escape(", ".join(w.get("missing_sections") or ["無"]))}</p><p><strong>PM 動作：</strong>{escape(str(w.get("pm_readable_action")))}</p><span class="badge {badge(str(w.get("freshness_status")))}">{escape(str(w.get("freshness_label")))}</span></article>')
    stock_cards=[]
    for s in stock_rows[:12]: stock_cards.append(f'<div class="source-item"><h3>{escape(str(s.get("stock_id")))} {escape(str(s.get("stock_name") or ""))}</h3><p>來源：{escape(str(s.get("source") or s.get("source_artifact_or_table") or "資料待接"))}</p><p>更新：{escape(str(s.get("latest_report_timestamp") or s.get("last_updated") or "missing"))}</p><span class="badge {badge(str(s.get("freshness_status")))}">{escape(str(s.get("freshness_label")))}</span></div>')
    stock_html=''.join(stock_cards) if stock_cards else '<div class="source-item"><h3>資料待接</h3><p>目前尚未找到可用追蹤標的資料。</p></div>'
    style=":root{--ink:#132227;--line:#d8e2e6;--ok:#e8f5ee;--warn:#fff7e5;--blue:#e9f3fb}*{box-sizing:border-box}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f4f7f8;color:var(--ink);line-height:1.55}header{background:linear-gradient(135deg,#103640,#1d5a63);color:#fff;padding:26px 16px 22px}main{max-width:1120px;margin:0 auto;padding:16px}h1{font-size:clamp(28px,4vw,44px);margin:0 0 8px}h2{font-size:22px;margin:0 0 12px}h3{font-size:18px;margin:0 0 8px}p{margin:0 0 10px}.badge-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.badge{display:inline-flex;border-radius:999px;padding:6px 10px;background:#e9f3fb;color:#123b44;font-weight:700;font-size:14px;border:1px solid rgba(18,59,68,.18)}.badge.warn{background:var(--warn);color:#6e4d00}.badge.safe{background:var(--ok);color:#23533b}.card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:16px;margin:14px 0;box-shadow:0 1px 0 rgba(14,39,46,.04)}.hero{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;margin-top:-12px;box-shadow:0 8px 24px rgba(14,39,46,.08)}.grid,.source-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.window-card{display:flex;flex-direction:column;gap:8px;min-height:260px}.window-time{font-size:28px;font-weight:800;color:#123b44}.window-title{font-size:24px;font-weight:800}.preview-note{background:var(--blue);border:1px solid #c8dcea;border-radius:10px;padding:12px;color:#244f64}.source-item{border:1px solid var(--line);border-radius:10px;padding:12px;background:#fbfdfe}details{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px;margin:14px 0}summary{font-weight:800;cursor:pointer}.debug-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.debug-list span{background:#f6f8f9;border:1px solid #e0e7ea;border-radius:8px;padding:8px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}@media (max-width:760px){main{padding:12px}.grid,.source-grid,.debug-list{grid-template-columns:1fr}.window-time{font-size:24px}.window-title{font-size:21px}.hero,.card{border-radius:10px;padding:14px}}"
    return '<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>四時段 AI 決策儀表板</title><style>'+style+'</style></head><body><header><h1>四時段 AI 決策儀表板</h1><p>盤前、盤中、收盤快照、盤後檢討</p><div class="badge-row"><span class="badge warn">預覽版 / 尚未接正式即時資料</span><span class="badge">最新資料：'+latest_ts+'</span><span class="badge warn">'+global_status+'</span><span class="badge safe">不通知、不下單、不改策略</span></div></header><main><section class="hero"><h2>今日決策摘要</h2><p>這個頁面整合既有 production-generated artifacts、本機只讀 SQLite 摘要、freshness 狀態與四時段 Dashboard。若資料缺失或過期，會明確標示，不會產生假預測。</p><p class="preview-note">目前為預覽資料，尚未接正式 runtime data；本頁也安全匯出既有 runtime data，沒有執行 production pipeline。非投資建議，不會觸發通知或下單。</p><div class="badge-row"><span class="badge">追蹤標的 '+str(len(stock_rows))+'</span><span class="badge">可用資料 '+str(usable)+'</span><span class="badge warn">缺失區塊 '+str(missing)+'</span><span class="badge warn">過期區塊 '+str(stale)+'</span><span class="badge warn">預測欄位：'+escape(prediction_available)+'</span></div></section><section class="card"><h2>四個時段怎麼看</h2><div class="grid">'+''.join(window_cards)+'</div></section><section class="card"><h2>目前追蹤標的</h2><div class="source-grid">'+stock_html+'</div></section><section class="card"><h2>最新報告摘要</h2><div class="source-grid">'+cards(runtime.get('latest_reports',[]),'report')+'</div></section><section class="card"><h2>個股狀態摘要</h2><div class="source-grid">'+cards(runtime.get('per_stock_summaries',[])[:12],'stock')+'</div></section><section class="card"><h2>預測資料狀態</h2><div class="source-grid">'+cards(runtime.get('prediction_fields',[]),'field')+'</div></section><section class="card"><h2>實際結果 / 預測檢討狀態</h2><div class="source-grid">'+cards(runtime.get('actual_outcome_fields',[]),'field')+cards(runtime.get('prediction_review_fields',[]),'field')+'</div></section><section class="card"><h2>資料新鮮度</h2><div class="source-grid">'+cards(runtime.get('freshness_checks',[])[:18],'fresh')+'</div></section><section class="card"><h2>資料可信度與證據來源 / 資料來源可信度</h2><div class="source-grid">'+cards(runtime.get('source_quality',[]),'source')+'</div></section><details><summary>技術檢查 / Debug</summary><p>以下資訊保留給維運檢查，不是主要使用者閱讀區。</p><div class="debug-list"><span>route='+route_path+'</span><span>runtime export='+escape(str(runtime.get('production_runtime_export_ref') or 'missing'))+'</span><span>runtime keys: pre_open_0700 / intraday_1305 / pre_close_1335 / post_close_1500</span><span>ui concept: close_snapshot_1335 / prediction_review_1500</span><span>production_dashboard_publish_executed=false</span><span>no notification</span><span>no scheduler change</span><span>no DB write</span><span>no production pipeline</span><span>no trading</span><span>no rating/action/confidence/weight mutation</span><span>fabricated_market_data=false</span></div></details></main></body></html>'
def write_json(path:Path,payload:dict[str,Any])->None:
    path.parent.mkdir(parents=True,exist_ok=True); path.write_text(json.dumps(payload,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8')
