"""Build Dashboard Intelligence V1 artifacts from deterministic offline samples."""
from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict
from .card_builder import build_stock_card, summarize_stock_cards
from .diagnostics_policy import build_diagnostics, ensure_main_sections_are_safe
from .intelligence_schema import safety_summary
from .mobile_layout_policy import preview_metadata
from .section_builder import build_sections

def offline_sample_input() -> Dict[str, Any]:
    return {
        "schema_version": "1.0",
        "task_id": "AI-DEV-126",
        "generated_from": "deterministic_offline_sample",
        "source_artifact_summary": {"ai_dev_122_prediction_foundation": "sample_available", "ai_dev_123_explainability": "sample_available", "ai_dev_124_confidence_calibration": "sample_available", "ai_dev_125_factor_recommendation": "sample_available", "real_artifacts_required": False},
        "stocks": [
            {"stock_id": "2330", "stock_name": "台積電", "rating": "bullish", "score": 82, "action": "research_watch", "confidence": 0.82, "confidence_status": "high_but_over_confident_warning", "prediction_targets": {"same_day_high_low": "range_watch", "next_day_high_low": "positive_bias", "one_month_trend": "up", "three_month_trend": "up_with_primary_source_gap"}, "top_positive_factors": ["fundamental: revenue_guidance", "technical: momentum_breakout"], "top_negative_factors": ["macro: market_aggregate_pressure"], "missing_data_factors": ["management_interview_primary_source"], "missing_primary_sources": ["latest company guidance transcript"], "source_coverage_readiness": "partial_primary_gap", "source_coverage_score": 0.62, "calibration_warning": True, "adaptive_recommendation_summary": {"recommendation_id": "rec-003", "factor_group": "chip", "recommended_direction": "monitor", "major_factor": True, "production_mutation_allowed": False, "requires_human_review": True}, "review_status": "review_required"},
            {"stock_id": "2317", "stock_name": "鴻海", "rating": "neutral", "score": 61, "action": "hold_research", "confidence": 0.54, "confidence_status": "sample_insufficient", "prediction_targets": {"same_day_high_low": "not_available", "next_day_high_low": "mixed", "one_month_trend": "watch", "three_month_trend": "watch"}, "top_positive_factors": ["adr: market_context_cross_check"], "top_negative_factors": ["missing_data: incomplete supplier update"], "missing_data_factors": ["primary supplier channel check", "recent management guidance"], "missing_primary_sources": ["primary supplier update"], "source_coverage_readiness": "insufficient_primary_source", "source_coverage_score": 0.48, "calibration_warning": False, "adaptive_recommendation_summary": {"recommendation_id": "rec-007", "factor_group": "missing_data", "recommended_direction": "monitor", "major_factor": False, "production_mutation_allowed": False, "requires_human_review": True}, "review_status": "insufficient_sample"},
        ],
        "prediction_performance": {"confidence_summary": {"status": "sample_demo", "high_confidence_bucket": "over_confident_sample_warning", "insufficient_sample_visible": True}, "weighted_ece": 0.118, "bucket_findings": [{"bucket": "0.80-1.00", "finding": "over_confident_sample_warning", "sample_size": 12}, {"bucket": "0.40-0.60", "finding": "insufficient_sample", "sample_size": 4}], "rating_effectiveness_summary": "Bullish sample cards require source coverage review before trust is raised.", "action_effectiveness_summary": "Actions are research labels only, not trading instructions.", "sample_size_warning": "offline sample/demo only; not production conclusion"},
        "source_coverage": {"source_coverage_summary": "Primary source partial; FinMind and yfinance shown only as supporting context.", "primary_source_status": "partial", "aggregated_source_status": "supporting_only", "market_context_status": "available_as_cross_check", "missing_primary_sources": ["latest company guidance transcript", "primary supplier update"], "finmind_yfinance_policy_note": "FinMind and yfinance are market-context/supporting sources, not primary authority.", "source_conflicts": ["news sentiment conflicts with primary-source gap"], "confidence_cap_reasons": ["missing primary source", "news-only evidence cannot act as rating authority"]},
        "explainability": {"top_positive_factors": ["fundamental: revenue guidance", "technical: momentum breakout"], "top_negative_factors": ["macro: aggregate pressure"], "neutral_factors": ["ADR market context"], "missing_data_factors": ["management interview", "supplier channel check"], "evidence_summary": "Deterministic sample evidence only; no invented evidence.", "source_ids": ["company_filing", "sqlite_historical_csv", "finmind_market", "yfinance_adr", "google_news_rss"], "evidence_ids": ["ev-sample-2330-001", "ev-sample-2317-001"], "explainability_status": "available_sample"},
        "confidence_calibration": {"confidence_bucket": "0.80-1.00", "finding": "over_confident_sample_warning", "calibration_gap": 0.18, "sample_size": 12, "weighted_ece": 0.118, "recommendation_summary": "Show warning and require review before trust increase.", "limitations": ["offline sample/demo only", "not a production model conclusion"]},
        "factor_recommendation": {"summary": "Monitor chip factor, decrease macro pressure influence in future review, never auto-apply.", "recommendations": [{"recommendation_id": "rec-001", "target_area": "factor_weight", "factor_group": "fundamental", "recommended_direction": "increase", "recommended_delta_range": "0 to +5% advisory", "confidence": 0.74, "sample_size": 24, "finding": "effective", "limitations": ["human review required"], "production_mutation_allowed": False, "requires_human_review": True}, {"recommendation_id": "rec-003", "target_area": "factor_weight", "factor_group": "chip", "recommended_direction": "monitor", "recommended_delta_range": "0%", "confidence": 0.52, "sample_size": 20, "finding": "weakly_effective", "limitations": ["marginal dry-run signal"], "production_mutation_allowed": False, "requires_human_review": True}, {"recommendation_id": "rec-004", "target_area": "factor_weight", "factor_group": "macro", "recommended_direction": "decrease", "recommended_delta_range": "0 to -5% advisory", "confidence": 0.60, "sample_size": 20, "finding": "inverted", "limitations": ["market context only"], "production_mutation_allowed": False, "requires_human_review": True}]},
        "diagnostics": {"pipeline_status": "offline_sample", "validation_status": "sample_valid", "missing_artifacts": ["real AI-DEV-122 rolling evaluation artifact"], "warnings": ["real artifacts unavailable; deterministic offline sample used"], "errors": ["Pipeline wrapper error summarized; raw traceback is intentionally suppressed"], "raw_error": "Traceback (most recent call last): sample pipeline wrapper error"},
    }

def build_artifact(payload: Dict[str, Any] | None = None) -> Dict[str, Any]:
    payload = payload or offline_sample_input()
    generated_at = datetime.now(timezone.utc).isoformat()
    stock_cards = [build_stock_card(stock) for stock in payload.get("stocks", [])]
    sections = build_sections(payload, stock_cards, generated_at)
    diagnostics = build_diagnostics(payload)
    safe_sections = ensure_main_sections_are_safe(sections)
    return {"schema_version": "1.0", "task_id": "AI-DEV-126", "artifact_type": "dashboard_intelligence_v1", "generated_at": generated_at, "source_artifact_summary": payload.get("source_artifact_summary", {}), "input_summary": {"stock_count": len(stock_cards), "source": payload.get("generated_from", "provided_payload"), "missing_real_artifacts_allowed": True}, "dashboard_status": "ready_for_repo_preview" if safe_sections else "diagnostics_review_required", "sections": sections, "stock_cards": stock_cards, "stock_card_summary": summarize_stock_cards(stock_cards), "prediction_performance_summary": payload.get("prediction_performance", {}), "source_coverage_summary": payload.get("source_coverage", {}), "explainability_summary": payload.get("explainability", {}), "confidence_calibration_summary": payload.get("confidence_calibration", {}), "factor_recommendation_summary": payload.get("factor_recommendation", {}), "diagnostics": diagnostics, "safety_summary": safety_summary(), "preview_metadata": preview_metadata(), "future_integration": {"ai_dev_127_ready": True, "real_artifact_ingestion_next": True, "production_publish_requires_separate_human_gated_task": True}, "advisory_only": True, "production_publish_allowed": False, "production_mutation_allowed": False}
