#!/usr/bin/env python3
"""Mobile GitHub Issue auto-pickup v1 for safe repo-only tasks.

This entrypoint is intentionally narrow:

* live mode reads open GitHub Issues with gh only;
* Issue text is task description, never shell;
* repo execution writes one sanitized repo artifact generated by this code;
* comment-back and label mutation are disabled unless explicit flags are used.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_STATE_DIR = Path("/home/kaochuchian/.local/state/stock-ai-orchestrator")
DEFAULT_MAX_ISSUES = 1
REQUIRED_LABELS = ["ai-dev", "gcp-pickup", "auto-run", "repo-only"]
APPROVAL_LABELS = {"dry-run", "approved-auto-run"}
BLOCKED_LABELS = {
    "runtime",
    "production",
    "secret",
    "notification",
    "trading",
    "n8n",
    "dify",
    "db",
    "cron",
    "systemd",
    "timer",
    "pipeline",
    "credential",
    "env",
}
ALLOWED_TASK_CLASSES = {
    "docs_only",
    "template_only",
    "validator_only",
    "repo_side_contract",
    "test_or_validation_helper",
    "runbook_only",
    "inspector_only",
}
BLOCKED_CLASS_PATTERNS = {
    "secret_handling": re.compile(r"(?i)\b(secret|token|credential|password|private key|\.env|api key)\b"),
    "Dify_runtime_call": re.compile(r"(?i)\bdify\b"),
    "OpenAI_API_call": re.compile(r"(?i)\b(openai|chatgpt)\b.*\b(api|call|run|execute)\b"),
    "notification_send": re.compile(r"(?i)\b(send|push|deliver)\b.*\b(line|email|notification|webhook)\b"),
    "trading_or_order": re.compile(r"(?i)\b(trade|trading|place order|order execution|buy order|sell order)\b"),
    "production_DB_mutation": re.compile(r"(?i)\b(db|database)\b.*\b(write|mutate|modify|update|delete|production)\b"),
    "n8n_control": re.compile(r"(?i)\bn8n\b"),
    "production_pipeline": re.compile(r"(?i)\b(production pipeline|python3 main\.py|run_stock_analysis\.sh|pipeline)\b"),
    "cron_systemd_timer_change": re.compile(r"(?i)\b(cron|systemd|timer|timers)\b"),
    "daemon_background_service": re.compile(r"(?i)\b(daemon|background service|polling worker)\b"),
    "runtime_action": re.compile(r"(?i)\b(runtime action|execute runtime|production runtime|real runtime)\b"),
    "arbitrary_shell_execution": re.compile(r"(?i)\b(shell|bash|sh -c|sudo|chmod|curl|wget|eval)\b"),
}
SECRET_VALUE_PATTERNS = [
    re.compile(r"ghp_[A-Za-z0-9_]+"),
    re.compile(r"github_pat_[A-Za-z0-9_]+"),
    re.compile(r"sk-[A-Za-z0-9_-]{12,}"),
    re.compile(r"xox[baprs]-[A-Za-z0-9-]+"),
    re.compile(r"Bearer\s+[A-Za-z0-9._~+/=-]{8,}", re.IGNORECASE),
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"(?i)(api[_-]?key|access[_-]?token|password)\s*[:=]\s*[^\s,}\"']+"),
]
ROLLBACK_COMMANDS = [
    "systemctl --user disable --now stock-ai-github-issue-scheduled-pickup-dry-run.timer",
    "systemctl --user reset-failed stock-ai-github-issue-scheduled-pickup-dry-run.service",
    "systemctl --user daemon-reload",
]


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def run_id() -> str:
    return f"mobile-auto-pickup-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"


def run_cmd(args: list[str], cwd: Path | None = None, timeout: int = 120) -> tuple[int, str, str]:
    proc = subprocess.run(args, cwd=str(cwd) if cwd else None, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False, timeout=timeout)
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def normalize_label(label: Any) -> str:
    if isinstance(label, dict):
        value = label.get("name", "")
    else:
        value = label
    return str(value).strip().lower()


def labels_for(issue: dict[str, Any]) -> list[str]:
    labels = issue.get("labels", [])
    if not isinstance(labels, list):
        return []
    return [label for label in (normalize_label(item) for item in labels) if label]


def find_secret_patterns(issue: dict[str, Any]) -> list[str]:
    text = json.dumps(issue, ensure_ascii=False, sort_keys=True)
    return [pattern.pattern for pattern in SECRET_VALUE_PATTERNS if pattern.search(text)]


def find_blocked_classes(title: str, body: str) -> list[str]:
    text = f"{title}\n{body}"
    text = re.sub(r"(?i)\b(no|not|without)\s+(real\s+)?runtime action\b", "", text)
    text = re.sub(r"(?i)\b(no|not|without)\s+production\s+(action|pipeline|db|database)\b", "", text)
    text = re.sub(r"(?i)\b(no|not|without)\s+(issue\s+)?(comment|label|mutation|close|reopen)\b", "", text)
    return [name for name, pattern in BLOCKED_CLASS_PATTERNS.items() if pattern.search(text)]


def classify_task(labels: list[str], title: str, body: str, blocked: list[str]) -> str:
    if blocked:
        return blocked[0]
    label_set = set(labels)
    text = f"{title}\n{body}".lower()
    if "inspector" in label_set or "inspector" in text or "health" in text:
        return "inspector_only"
    if "runbook" in label_set or "runbook" in text:
        return "runbook_only"
    if "validator" in label_set or "validator" in text:
        return "validator_only"
    if "template" in label_set or "template" in text:
        return "template_only"
    if "docs" in label_set or "documentation" in text or "doc" in text:
        return "docs_only"
    if "test" in label_set or "validation helper" in text or "test helper" in text:
        return "test_or_validation_helper"
    if "contract" in label_set or "contract" in text:
        return "repo_side_contract"
    return "needs_manual_review"


def sanitize_title(value: Any) -> str:
    title = str(value or "").replace("\n", " ").strip()
    return title[:160]


def idempotency_key(issue: dict[str, Any], task_class: str, labels: list[str]) -> str:
    issue_number = issue.get("issue_number", issue.get("number"))
    issue_url = str(issue.get("issue_url", issue.get("url", issue.get("html_url", ""))))
    present_required = ",".join(label for label in REQUIRED_LABELS if label in labels)
    approval = ",".join(label for label in sorted(APPROVAL_LABELS & set(labels)))
    return f"mobile-auto-pickup-v1|{issue_number}|{issue_url}|{task_class}|{present_required}|{approval}"


def load_json(path: Path) -> tuple[dict[str, Any] | None, list[str]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return None, [f"failed to parse JSON: {exc}"]
    if not isinstance(data, dict):
        return None, ["JSON root must be an object"]
    return data, []


def load_idempotency(path: Path) -> dict[str, Any]:
    data, errors = load_json(path)
    if data is None or errors:
        return {"schema_version": "1.0.0", "processed_keys": []}
    keys = data.get("processed_keys")
    if not isinstance(keys, list):
        data["processed_keys"] = []
    return data


def save_idempotency(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def read_fixture(path: Path) -> tuple[list[dict[str, Any]], list[str]]:
    data, errors = load_json(path)
    if data is None:
        return [], errors
    issues = data.get("issues")
    if issues is None and any(key in data for key in ("number", "issue_number", "title")):
        issues = [data]
    if not isinstance(issues, list):
        return [], ["fixture must include issues list or one issue object"]
    return [issue for issue in issues if isinstance(issue, dict)], []


def read_live_issues(repo: str | None, limit: int) -> tuple[list[dict[str, Any]], list[str]]:
    args = [
        "gh",
        "issue",
        "list",
        "--state",
        "open",
        "--limit",
        str(max(limit, 1)),
        "--json",
        "number,url,state,title,body,labels,createdAt,updatedAt",
    ]
    for label in REQUIRED_LABELS:
        args.extend(["--label", label])
    if repo:
        args.extend(["--repo", repo])
    code, stdout, stderr = run_cmd(args, timeout=60)
    if code != 0:
        return [], [stderr or stdout or "gh issue list failed"]
    try:
        raw = json.loads(stdout)
    except Exception as exc:
        return [], [f"failed to parse gh issue list JSON: {exc}"]
    if not isinstance(raw, list):
        return [], ["gh issue list JSON root must be a list"]
    return [item for item in raw if isinstance(item, dict)], []


def evaluate_issue(issue: dict[str, Any], processed_keys: set[str]) -> dict[str, Any]:
    labels = labels_for(issue)
    label_set = set(labels)
    title = sanitize_title(issue.get("title"))
    body = str(issue.get("body", ""))
    state = str(issue.get("state", "")).lower()
    missing_labels = [label for label in REQUIRED_LABELS if label not in label_set]
    missing_approval = sorted(APPROVAL_LABELS - label_set) if not (APPROVAL_LABELS & label_set) else []
    blocked_label_hits = [f"blocked_label:{label}" for label in sorted(BLOCKED_LABELS & label_set)]
    blocked_classes = find_blocked_classes(title, body)
    secret_hits = find_secret_patterns(issue)
    task_class = classify_task(labels, title, body, blocked_label_hits + blocked_classes)
    key = idempotency_key(issue, task_class, labels)
    blocked_terms = blocked_label_hits + blocked_classes
    if secret_hits and "secret_handling" not in blocked_terms:
        blocked_terms.append("secret_handling")
    if state != "open":
        blocked_terms.append("issue_not_open")
    if key in processed_keys:
        blocked_terms.append("already_processed")
    task_class_allowed = task_class in ALLOWED_TASK_CLASSES
    eligible = (
        state == "open"
        and not missing_labels
        and not missing_approval
        and not blocked_label_hits
        and not blocked_classes
        and not secret_hits
        and task_class_allowed
        and key not in processed_keys
    )
    if eligible:
        decision = "accepted"
        summary = f"Accepted mobile Issue candidate for {task_class} repo-only automation."
    elif "already_processed" in blocked_terms:
        decision = "already_processed"
        summary = "Skipped mobile Issue candidate because its idempotency key already has a terminal result."
    elif blocked_terms or secret_hits:
        decision = "rejected"
        summary = "Rejected mobile Issue candidate because blocked labels, blocked terms, or sensitive value patterns were detected."
    else:
        decision = "needs_manual_review"
        summary = "Mobile Issue candidate needs manual review before repo-only automation."
    return {
        "issue_number": issue.get("issue_number", issue.get("number")),
        "issue_url": str(issue.get("issue_url", issue.get("url", issue.get("html_url", "")))),
        "title": title,
        "labels_seen": labels,
        "eligible": eligible,
        "decision": decision,
        "task_class": task_class,
        "required_labels_present": not missing_labels,
        "approval_label_present": not missing_approval,
        "blocked_terms_detected": blocked_terms,
        "idempotency_key": key,
        "sanitized_summary": summary,
        "execute_repo_only_allowed": eligible,
    }


def git_clean(repo_root: Path) -> bool:
    code, stdout, _ = run_cmd(["git", "status", "--short"], cwd=repo_root)
    return code == 0 and stdout == ""


def current_branch(repo_root: Path) -> str:
    code, stdout, _ = run_cmd(["git", "branch", "--show-current"], cwd=repo_root)
    return stdout if code == 0 else ""


def write_execution_artifact(repo_root: Path, record: dict[str, Any], rid: str) -> Path:
    issue_number = record.get("issue_number") or "unknown"
    path = repo_root / "docs" / "mobile_issue_auto_runs" / f"issue_{issue_number}_{rid}.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    artifact = {
        "schema_version": "1.0.0",
        "run_id": rid,
        "generated_at": utc_now(),
        "issue_number": record.get("issue_number"),
        "issue_url": record.get("issue_url"),
        "title": record.get("title"),
        "task_class": record.get("task_class"),
        "decision": "executed_repo_only",
        "sanitized_summary": "Controlled repo-only automation wrote this sanitized execution artifact.",
        "runtime_action_performed": False,
        "production_action_performed": False,
        "github_issue_mutated": False,
    }
    path.write_text(json.dumps(artifact, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def checks_success(status_rollup: Any) -> bool:
    if not isinstance(status_rollup, list):
        return False
    if not status_rollup:
        return True
    for item in status_rollup:
        if not isinstance(item, dict):
            return False
        if item.get("status") != "COMPLETED":
            return False
        if item.get("conclusion") not in {"SUCCESS", "SKIPPED", "NEUTRAL"}:
            return False
    return True


def execute_repo_only(repo_root: Path, record: dict[str, Any], rid: str, repo: str | None) -> dict[str, Any]:
    result = {
        "branch_created": False,
        "pr_created": False,
        "pr_url": None,
        "merged": False,
        "merge_commit": None,
        "files_changed": [],
        "validations_run": [],
        "github_actions_result": "not_run",
        "errors": [],
    }
    if current_branch(repo_root) != "main":
        result["errors"].append("repo-only execution requires current branch main")
        return result
    if not git_clean(repo_root):
        result["errors"].append("repo-only execution requires clean git status")
        return result

    branch = f"ai-dev/mobile-issue-{record.get('issue_number')}-{rid.lower()}"
    code, _, stderr = run_cmd(["git", "switch", "-c", branch], cwd=repo_root)
    if code != 0:
        result["errors"].append(stderr or "failed to create branch")
        return result
    result["branch_created"] = True
    try:
        artifact_path = write_execution_artifact(repo_root, record, rid)
        rel_path = str(artifact_path.relative_to(repo_root))
        result["files_changed"].append(rel_path)
        validations = [
            ["python3", "-m", "py_compile", "scripts/orchestrator/github_issue_mobile_auto_pickup.py", "scripts/orchestrator/validate_github_issue_mobile_auto_pickup_result.py"],
            ["python3", "-m", "json.tool", rel_path],
            ["git", "diff", "--check", "main...HEAD"],
        ]
        for command in validations:
            code, stdout, stderr = run_cmd(command, cwd=repo_root, timeout=120)
            result["validations_run"].append({"command": " ".join(command), "passed": code == 0})
            if code != 0:
                result["errors"].append(stderr or stdout or f"validation failed: {' '.join(command)}")
                return result
        run_cmd(["git", "add", rel_path], cwd=repo_root)
        code, _, stderr = run_cmd(["git", "commit", "-m", f"AI-DEV mobile issue {record.get('issue_number')} sanitized execution artifact"], cwd=repo_root)
        if code != 0:
            result["errors"].append(stderr or "commit failed")
            return result
        code, _, stderr = run_cmd(["git", "push", "-u", "origin", branch], cwd=repo_root, timeout=120)
        if code != 0:
            result["errors"].append(stderr or "push failed")
            return result
        pr_body = (
            "## Summary\n"
            "- Add sanitized execution artifact for mobile GitHub Issue auto-pickup.\n\n"
            "## Safety\n"
            "- Repo-only generated artifact.\n"
            "- No Issue mutation, no runtime action, no production action.\n"
        )
        pr_args = ["gh", "pr", "create", "--base", "main", "--head", branch, "--title", f"Mobile Issue {record.get('issue_number')} repo-only artifact", "--body", pr_body]
        if repo:
            pr_args.extend(["--repo", repo])
        code, stdout, stderr = run_cmd(pr_args, cwd=repo_root, timeout=120)
        if code != 0:
            result["errors"].append(stderr or stdout or "PR creation failed")
            return result
        result["pr_created"] = True
        result["pr_url"] = stdout.splitlines()[-1] if stdout else None
        pr_ref = result["pr_url"] or branch
        for _ in range(18):
            view_args = ["gh", "pr", "view", str(pr_ref), "--json", "number,isDraft,mergeStateStatus,statusCheckRollup,url"]
            if repo:
                view_args.extend(["--repo", repo])
            code, stdout, _ = run_cmd(view_args, cwd=repo_root, timeout=60)
            if code == 0:
                data = json.loads(stdout)
                if not data.get("isDraft") and data.get("mergeStateStatus") == "CLEAN" and checks_success(data.get("statusCheckRollup")):
                    result["github_actions_result"] = "success"
                    merge_args = ["gh", "pr", "merge", str(data["number"]), "--merge", "--delete-branch"]
                    if repo:
                        merge_args.extend(["--repo", repo])
                    code, _, stderr = run_cmd(merge_args, cwd=repo_root, timeout=120)
                    if code != 0:
                        result["errors"].append(stderr or "PR merge failed")
                        return result
                    info_args = ["gh", "pr", "view", str(data["number"]), "--json", "mergeCommit"]
                    if repo:
                        info_args.extend(["--repo", repo])
                    code, stdout, _ = run_cmd(info_args, cwd=repo_root, timeout=60)
                    if code == 0:
                        info = json.loads(stdout)
                        result["merge_commit"] = (info.get("mergeCommit") or {}).get("oid")
                    result["merged"] = True
                    run_cmd(["git", "switch", "main"], cwd=repo_root)
                    run_cmd(["git", "pull", "--ff-only"], cwd=repo_root, timeout=120)
                    return result
                if data.get("mergeStateStatus") in {"DIRTY", "UNKNOWN"}:
                    result["github_actions_result"] = str(data.get("mergeStateStatus")).lower()
            time.sleep(10)
        result["errors"].append("PR did not reach CLEAN successful checks before timeout")
        return result
    finally:
        run_cmd(["git", "switch", "main"], cwd=repo_root)


def build_base_result(rid: str, source: str, issues_seen: int, evaluated: list[dict[str, Any]], rejected: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "schema_version": "1.0.0",
        "run_id": rid,
        "generated_at": utc_now(),
        "source": source,
        "dry_run": True,
        "scheduler_enabled": False,
        "total_issues_seen": issues_seen,
        "eligible_count": len(evaluated),
        "rejected_count": len([item for item in rejected if item.get("decision") == "rejected"]),
        "needs_manual_review_count": len([item for item in rejected if item.get("decision") == "needs_manual_review"]),
        "candidate_issue_numbers": [item.get("issue_number") for item in evaluated],
        "selected_issue_number": None,
        "selected_issue_url": None,
        "task_class": None,
        "decision": "no_candidate",
        "branch_created": False,
        "pr_created": False,
        "pr_url": None,
        "merged": False,
        "merge_commit": None,
        "files_changed": [],
        "validations_run": [],
        "github_actions_result": "not_run",
        "issue_comment_created": False,
        "issue_labels_changed": False,
        "github_issue_mutated": False,
        "runtime_action_performed": False,
        "production_action_performed": False,
        "daemon_or_background_service_created": False,
        "candidates": evaluated,
        "rejected": rejected,
        "idempotency_keys": [item.get("idempotency_key") for item in evaluated],
        "rollback_or_disable_commands": ROLLBACK_COMMANDS,
        "next_step_recommendation": "No eligible mobile Issue candidate was selected.",
        "safety_confirmation": "No runtime action, production action, Issue mutation, comment-back, label mutation, n8n, Dify, notification, production DB, trading, or shell execution from Issue text was performed.",
        "errors": [],
        "warnings": [],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Mobile GitHub Issue auto-pickup end-to-end v1.")
    parser.add_argument("--once", action="store_true", help="Required guard; no daemon or polling loop is implemented.")
    parser.add_argument("--pretty", action="store_true")
    parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR))
    parser.add_argument("--repo", default=None, help="GitHub repo OWNER/NAME for gh commands.")
    parser.add_argument("--input", help="Sanitized fixture with issues list.")
    parser.add_argument("--output", required=True)
    parser.add_argument("--max-issues", type=int, default=DEFAULT_MAX_ISSUES)
    parser.add_argument("--live-read-open-issues", action="store_true")
    parser.add_argument("--dry-run", action="store_true", default=True)
    parser.add_argument("--execute-repo-only", action="store_true")
    parser.add_argument("--comment-back", action="store_true")
    parser.add_argument("--no-comment-back", action="store_true", default=True)
    parser.add_argument("--label-closeout", action="store_true")
    parser.add_argument("--no-label-mutation", action="store_true", default=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    state_dir = Path(args.state_dir)
    state_dir.mkdir(parents=True, exist_ok=True)
    rid = run_id()
    errors: list[str] = []
    if not args.once:
        errors.append("--once is required")
    if args.max_issues != 1:
        errors.append("v1 requires --max-issues 1")
    if args.comment_back:
        errors.append("comment-back remains disabled for scheduled v1")
    if args.label_closeout:
        errors.append("label mutation remains disabled for scheduled v1")
    if not args.live_read_open_issues and not args.input:
        errors.append("provide --live-read-open-issues or --input")

    source = "live_read" if args.live_read_open_issues else "fixture"
    issues: list[dict[str, Any]] = []
    if not errors:
        if args.live_read_open_issues:
            issues, errors = read_live_issues(args.repo, args.max_issues)
        else:
            issues, errors = read_fixture(Path(str(args.input)))

    idempotency_path = state_dir / "github_issue_mobile_auto_pickup_idempotency.json"
    idempotency = load_idempotency(idempotency_path)
    processed_keys = set(str(key) for key in idempotency.get("processed_keys", []) if isinstance(key, str))
    evaluated_all = [evaluate_issue(issue, processed_keys) for issue in issues[: args.max_issues]]
    candidates = [item for item in evaluated_all if item.get("eligible") is True]
    rejected = [item for item in evaluated_all if item.get("eligible") is not True]
    result = build_base_result(rid, source, len(evaluated_all), candidates, rejected)
    result["errors"].extend(errors)

    selected = candidates[0] if candidates else None
    if selected:
        result["selected_issue_number"] = selected.get("issue_number")
        result["selected_issue_url"] = selected.get("issue_url")
        result["task_class"] = selected.get("task_class")
        result["decision"] = "accepted"
        result["next_step_recommendation"] = "Eligible candidate selected; repo-only execution was not requested."
        if args.execute_repo_only and "approved-auto-run" in selected.get("labels_seen", []):
            exec_result = execute_repo_only(Path.cwd(), selected, rid, args.repo)
            result.update({key: exec_result[key] for key in ["branch_created", "pr_created", "pr_url", "merged", "merge_commit", "files_changed", "validations_run", "github_actions_result"]})
            result["errors"].extend(exec_result.get("errors", []))
            result["decision"] = "executed_repo_only" if exec_result.get("merged") else "needs_manual_review"
            result["next_step_recommendation"] = "Repo-only artifact PR was merged." if exec_result.get("merged") else "Review execution errors before retrying."
        elif args.execute_repo_only:
            result["decision"] = "accepted"
            result["warnings"].append("repo-only execution requires approved-auto-run label; dry-run label alone remains discovery-only")
            result["next_step_recommendation"] = "Add approved-auto-run label after reviewing the Issue, then rerun."

        if result["decision"] in {"executed_repo_only", "accepted"} and not result["errors"]:
            processed_keys.add(str(selected.get("idempotency_key")))
            idempotency["processed_keys"] = sorted(processed_keys)
            idempotency["updated_at"] = utc_now()
            save_idempotency(idempotency_path, idempotency)

    state_candidate_path = state_dir / "github_issue_mobile_auto_pickup_latest_candidate.json"
    state_result_path = state_dir / "github_issue_mobile_auto_pickup_latest.json"
    state_candidate_path.write_text(json.dumps({"run_id": rid, "candidates": candidates, "rejected": rejected}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    text = json.dumps(result, ensure_ascii=False, indent=2 if args.pretty else None) + "\n"
    state_result_path.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text, encoding="utf-8")
    sys.stdout.write(text if args.pretty else json.dumps({"ok": not result["errors"], "output": str(output_path), "decision": result["decision"]}) + "\n")
    return 0 if not result["errors"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
